---
- name: Deploy Bawdy
  hosts: ceto
  become: yes

  roles:
    - role: docker_service
      vars:
        service_name: bawdy
        compose_template: bawdy-compose.yml.j2
        service_directories:
          - config
          - path: sequences
            mode: "0777"
        docker_compose_state: present
